version: '3.3'
x-rails-base: &rails_base
  environment:
    RAILS_ENV: production
    RACK_ENV: production
    NODE_ENV: production
    RAILS_MASTER_KEY: 7cd690550b21a176659d2e098bc495a3
    APP_DATABASE_HOST: ${APP_DATABASE_HOST}
    APP_DATABASE_PORT: ${APP_DATABASE_PORT}
    APP_DATABASE_NAME: ${APP_DATABASE_NAME}
    APP_DATABASE_USERNAME: ${APP_DATABASE_USERNAME}
    APP_DATABASE_PASSWORD: ${APP_DATABASE_PASSWORD}
    REDIS_HOST: ${REDIS_HOST}
    REDIS_PORT: ${REDIS_PORT}
    REDIS_PASSWORD: ${REDIS_PASSWORD}
    API_KEY: ${API_KEY}
    SECRET_TOKEN: ${SECRET_TOKEN}
services:
  backend:
    <<: *rails_base
    build:
      context: .
      dockerfile: ./Dockerfile.azure
    image: miyoshibackend.azurecr.io/miyoshibackend:latest
    container_name: backend
    ports:
      - 80:3000
  worker:
    <<: *rails_base
    build:
      context: .
      dockerfile: ./Dockerfile.worker.azure
    image: miyoshibackend.azurecr.io/miyoshiworker:latest
    container_name: worker
