---
openapi: 3.0.1
info:
  title: データダウンロードAPI定義
  version: v1
  description: |-
    リクエストヘッダーに設定するアクセストークンは、HMAC-SHA256を使用して発行する。

    [アクセストークン発行のサンプル](https://github.com/cm-manage/miyoshi-doc/wiki/%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E7%99%BA%E8%A1%8C%E3%81%AE%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB)
    
servers:
- url: https://miyoshibackend.azurewebsites.net/api
paths:
  /v1/downloads/parkings:
    get:
      operationId: parking_downloads
      summary: 駐車場データダウンロード
      description: 駐車場データダウンロード
      parameters:
        - name: from_year_month
          in: query
          description: from_year_month
          required: true
          schema:
            type: string
        - name: to_year_month
          in: query
          description: to_year_month
          required: true
          schema:
            type: string
      responses:
        200:
          description: 'OK.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParkingDataList'
        400:
          description: 'Bad Request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponse'
        401:
          description: 'Unauthorized.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorResponse'
        500:
          description: 'InternalServerError.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResponse'
      security:
      - api_key: []

  /v1/downloads/chatbots:
    get:
      operationId: chatbot_data_downloads
      summary: 観光案内チャットボットサービス利用データダウンロード
      description: 観光案内チャットボットサービス利用データダウンロード
      parameters:
        - name: from_year_month
          in: query
          description: from_year_month
          required: true
          schema:
            type: string
        - name: to_year_month
          in: query
          description: to_year_month
          required: true
          schema:
            type: string
      responses:
        200:
          description: 'OK.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatbotDataList'
        400:
          description: 'Bad Request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponse'
        401:
          description: 'Unauthorized.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorResponse'
        500:
          description: 'InternalServerError.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResponse'
      security:
      - api_key: []
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: access-token
      in: header
  schemas:
    BadRequestErrorResponse:
      properties:
        errors:
          type: array
          example: [ "400 BadRequest" ]
    UnauthorizedErrorResponse:
      type: object
      properties:
        errors:
          type: array
          example: [ "401 Unauthorized." ]
    InternalServerErrorResponse:
      type: object
      properties:
        errors:
          type: array
          example: [ "500 Internal Server Error." ]
    ParkingDataList:
      type: array
      items:
        $ref: '#/components/schemas/ParkingData'
    ParkingData:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        in_out_flg:
          type: boolean
          example: true
        parking_time:
          type: string
          example: "2023-02-13T00:13:00.000+09:00"
        car_area:
          type: string
          example: "品川"
        car_number:
          type: string
          example: "な3066 20-86"
        created_at:
          type: string
          example: "2023-03-27T18:25:53.510+09:00"
        updated_at:
          type: string
          example: "2023-03-27T18:25:53.510+09:00"
    ChatbotDataList:
      type: array
      items:
        $ref: '#/components/schemas/ChatbotData'
    ChatbotData:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        conversation_at:
          type: string
          example: "2023-01-12T10:18:53.000+09:00"
        user_id:
          type: string
          example: "U3fdd45231a049d17387c77e7245e289c"
        conversation_id:
          type: string
          example: "42551034"
        message:
          type: string
          example: "日本"
        button:
          type: string
          example: "ボタン"
        question_category_one:
          type: string
          example: "対象外"
        question_category_two:
          type: string
          example: "対象外"
        question_category_three:
          type: string
          example: "対象外"
        reply:
          type: boolean
          example: true
        language:
          type: string
          example: "zh-TW"
        area:
          type: string
          example: "三次市エリア"
        country:
          type: string
          example: "日本"
        residential_area:
          type: string
          example: "沖縄"
        user_interface:
          type: string
          example: "LINE"
        created_at:
          type: string
          example: "2023-03-28T10:31:02.601+09:00"
        updated_at:
          type: string
          example: "2023-03-28T10:31:02.601+09:00"